import Head from 'next/head';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import Header from '../components/layout/Header';
import AddBillData from '../components/billData/AddBillData';
import BillList from '../components/billList/BillList';
import Error from '../components/ui/Error';

export default function Home({user}) {
  
  const [darkMode, setDarkMode] = useState(false);
  const [billDataList, setBillDataList] = useState([]);
  const [billDescription, setBillDescription] = useState('');
  const [billAmount, setBillAmount] = useState(0);
  const [billDueDate, setBillDueDate] = useState('');
  const [paid, setPaid] = useState(false);
  const [billsTotal, setBillsTotal] = useState(0);
  const [formHidden, setFormHidden] = useState(false);
  const [error, setError] = useState('');
  
  useEffect(() => {
    const getLocalBillData = () => {
      const data = localStorage.getItem('billData');
      if(data) {
        return JSON.parse(data);
      }else {
        return [];
      }
    }
    
    // add check for bills totals
    const getLocalBillsTotal = () => {
      const data = localStorage.getItem('billsTotal');
      if(data) {
        return JSON.parse(data);
      }else {
        return 0;
      }
    }
    
    setBillsTotal(getLocalBillsTotal)
    setBillDataList(getLocalBillData);
  }, []);
  
  return (
    <div>
      <Head>
        <title>Glimpse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet" />
      </Head>
      
      <Header darkMode={darkMode} setDarkMode={setDarkMode} />
        {user}
      <div className="container">
        <div className="content-wrapper">
          <div className="row">
            <div className={formHidden === true ? 'hide-form' : 'col-md-6'}>
              <AddBillData 
                billDataList={billDataList} 
                setBillDataList={setBillDataList} 
                billDescription={billDescription}
                setBillDescription={setBillDescription}
                billAmount={billAmount}
                setBillAmount={setBillAmount}
                billDueDate={billDueDate}
                setBillDueDate={setBillDueDate}
                paid={paid}
                setPaid={setPaid}
                billsTotal={billsTotal}
                setBillsTotal={setBillsTotal}
                formHidden={formHidden}
                setFormHidden={setFormHidden}
                error={error}
                setError={setError}
              />
            </div>
            
            <div className={formHidden === true ? 'col-md-12' : 'col-md-6'}>
              <BillList 
                billDataList={billDataList} 
                setBillDataList={setBillDataList}
                paid={paid}
                setPaid={setPaid}
                billsTotal={billsTotal}
                setBillsTotal={setBillsTotal}
                formHidden={formHidden}
                setFormHidden={setFormHidden}
              />
            </div>
          </div>                              
        </div>        
      </div>
    
      <Error error={error} />      
    </div>
  )
}
